# Generated by Django 2.0 on 2018-01-16 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCreate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('summary', models.CharField(max_length=50, verbose_name='介绍')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('status', models.CharField(choices=[('0', '未开始'), ('1', '进行中'), ('2', '已结束'), ('3', '已删除'), ('4', '未参加'), ('5', '已参加')], default='0', max_length=1, verbose_name='活动状态')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ActivityJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_creater', models.BooleanField(default=False)),
                ('step', models.IntegerField(default=0, verbose_name='步数')),
                ('mileage', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='距离')),
                ('altitude', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='海拔')),
                ('calorie', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='卡路里')),
                ('status', models.CharField(choices=[('0', '未开始'), ('1', '进行中'), ('2', '已结束'), ('3', '已删除'), ('4', '未参加'), ('5', '已参加')], max_length=1, verbose_name='活动状态')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activity.ActivityCreate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
